//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RequestModel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RequestModel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Models.RequestModel", typeof(RequestModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional requests field is required.
        /// </summary>
        public static string Details_Required {
            get {
                return ResourceManager.GetString("Details_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional requests must be between 6 and 1000 characters.
        /// </summary>
        public static string Details_StringLength {
            get {
                return ResourceManager.GetString("Details_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address format.
        /// </summary>
        public static string Email_EmailAddress {
            get {
                return ResourceManager.GetString("Email_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address (e.g., user@example.com).
        /// </summary>
        public static string Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Email_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length must not exceed 100 characters.
        /// </summary>
        public static string Email_StringLength {
            get {
                return ResourceManager.GetString("Email_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an event date.
        /// </summary>
        public static string EventDate_Required {
            get {
                return ResourceManager.GetString("EventDate_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an event type.
        /// </summary>
        public static string EventType_Required {
            get {
                return ResourceManager.GetString("EventType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guests count must be a number (maximum 5 digits).
        /// </summary>
        public static string Guests_Invalid {
            get {
                return ResourceManager.GetString("Guests_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can only contain letters and spaces between them.
        /// </summary>
        public static string Name_InvalidCharacters {
            get {
                return ResourceManager.GetString("Name_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your name.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name must be between 2 and 50 characters.
        /// </summary>
        public static string Name_StringLength {
            get {
                return ResourceManager.GetString("Name_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number as +375-25/29/33/44-XXX-XX-XX.
        /// </summary>
        public static string Phone_InvalidFormat {
            get {
                return ResourceManager.GetString("Phone_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a valid phone number.
        /// </summary>
        public static string Phone_Phone {
            get {
                return ResourceManager.GetString("Phone_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your phone number as +375 (25/29/33/44) XXX-XX-XX.
        /// </summary>
        public static string Phone_Required {
            get {
                return ResourceManager.GetString("Phone_Required", resourceCulture);
            }
        }
    }
}
