//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Calculator {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Calculator() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Pages.Calculator", typeof(Calculator).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation (fabrique screen).
        /// </summary>
        public static string Animation {
            get {
                return ResourceManager.GetString("Animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam (3D show).
        /// </summary>
        public static string Beam {
            get {
                return ResourceManager.GetString("Beam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined (animation + beam).
        /// </summary>
        public static string Combined {
            get {
                return ResourceManager.GetString("Combined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Base price includes 2 hours of beam show and up to 5 minutes of animation show..
        /// </summary>
        public static string CombinedIncludedNote {
            get {
                return ResourceManager.GetString("CombinedIncludedNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.3.
        /// </summary>
        public static string DeliveryRateValue {
            get {
                return ResourceManager.GetString("DeliveryRateValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travel outside the city (distance in km).
        /// </summary>
        public static string DistanceLabel {
            get {
                return ResourceManager.GetString("DistanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per 1 km from the city.
        /// </summary>
        public static string DistanceNoteAfter {
            get {
                return ResourceManager.GetString("DistanceNoteAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery price:.
        /// </summary>
        public static string DistanceNoteBefore {
            get {
                return ResourceManager.GetString("DistanceNoteBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated Price.
        /// </summary>
        public static string EstimatedPrice {
            get {
                return ResourceManager.GetString("EstimatedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Exact price after consultation.
        /// </summary>
        public static string PriceNote {
            get {
                return ResourceManager.GetString("PriceNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Quote.
        /// </summary>
        public static string RequestQuote {
            get {
                return ResourceManager.GetString("RequestQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laser Show Type.
        /// </summary>
        public static string ShowType {
            get {
                return ResourceManager.GetString("ShowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Calculator.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
