//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FAQ {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAQ() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Pages.FAQ", typeof(FAQ).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A high-tech laser projector projects vibrant, dynamic graphics and storyline animations onto a special semi-transparent mesh screen in perfect synchronization with the music. This creates a stunning illusion of a 3D image floating in mid-air..
        /// </summary>
        public static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storyline animation shows are performed primarily indoors. This is because projection requires a special tension mesh screen that is sensitive to strong wind gusts. However, in calm, windless weather, projecting directly onto a flat building facade is possible..
        /// </summary>
        public static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absolutely! We can create a unique laser love story, a spectacular brand presentation, or a custom festive show based on your personal script, set to any music of your choice. Every detail of the video is coordinated with you step-by-step during the production process..
        /// </summary>
        public static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you choose a standard program from our library (e.g., classic wedding, New Year, or graduation theme), preparation takes 2 to 5 days. Creating a fully custom animation video from scratch based on your requirements requires 2 to 4 weeks of meticulous work by our animator..
        /// </summary>
        public static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, for a spatial beam show, having a light haze in the air is critical, as it makes the laser beams visible and spectacular. We use professional, safe haze generators (hazers). We always pre-coordinate their usage with your venue&apos;s management..
        /// </summary>
        public static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beam show is a powerful spatial performance. It is typically used as a spectacular musical interlude, a grand climax of the event, a dynamic opening for the dance floor, or to brilliantly highlight key moments of the entertainment program and contests..
        /// </summary>
        public static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It depends on your goals. If you want to tell a touching and romantic story of how you met — a graphical animation show on a screen is the ideal choice. If you want to spectacularly enhance the newlyweds&apos; first dance or energize the dance floor — a beam show will create an incredible, magical atmosphere. For the ultimate impact, we recommend the combined option..
        /// </summary>
        public static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How exactly is the animation laser show performed?.
        /// </summary>
        public static string Q1 {
            get {
                return ResourceManager.GetString("Q1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can the animation show be performed outdoors?.
        /// </summary>
        public static string Q2 {
            get {
                return ResourceManager.GetString("Q2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is it possible to develop a custom script and choose our own music?.
        /// </summary>
        public static string Q3 {
            get {
                return ResourceManager.GetString("Q3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How much time is needed to prepare the laser show?.
        /// </summary>
        public static string Q4 {
            get {
                return ResourceManager.GetString("Q4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is a fog or haze machine used during the performance?.
        /// </summary>
        public static string Q5 {
            get {
                return ResourceManager.GetString("Q5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is the beam show conducted at an event?.
        /// </summary>
        public static string Q6 {
            get {
                return ResourceManager.GetString("Q6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which is better for a wedding: a beam or animation show?.
        /// </summary>
        public static string Q7 {
            get {
                return ResourceManager.GetString("Q7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
