//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServicesAndPrices {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServicesAndPrices() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Pages.ServicesAndPrices", typeof(ServicesAndPrices).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projection of animated graphics, custom texts, logos, and stories onto screens, building facades, or water shields. An exceptional way to tell a love story at a wedding, present a brand at a corporate event, or create a major custom public installation..
        /// </summary>
        public static string AnimDesc {
            get {
                return ResourceManager.GetString("AnimDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animation Show.
        /// </summary>
        public static string AnimName {
            get {
                return ResourceManager.GetString("AnimName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from 350 BYN.
        /// </summary>
        public static string AnimPrice {
            get {
                return ResourceManager.GetString("AnimPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stunning 3D spatial performance right above the heads of your audience. High-power laser planes, waves, and beams move in perfect sync with dynamic music, creating an overwhelming effect of immersion. Perfect for concerts, festivals, and club parties..
        /// </summary>
        public static string BeamDesc {
            get {
                return ResourceManager.GetString("BeamDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beam Show.
        /// </summary>
        public static string BeamName {
            get {
                return ResourceManager.GetString("BeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from 200 BYN.
        /// </summary>
        public static string BeamPrice {
            get {
                return ResourceManager.GetString("BeamPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a Show.
        /// </summary>
        public static string BookButton {
            get {
                return ResourceManager.GetString("BookButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum visual scale! Combines detailed storytelling graphics on a screen with breathtaking 3D spatial beam effects. Your audience follows the narrative while feeling completely surrounded by laser beams. The ultimate choice for the climax of major events..
        /// </summary>
        public static string CombDesc {
            get {
                return ResourceManager.GetString("CombDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combined Show.
        /// </summary>
        public static string CombName {
            get {
                return ResourceManager.GetString("CombName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from 400 BYN.
        /// </summary>
        public static string CombPrice {
            get {
                return ResourceManager.GetString("CombPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Services &amp; Prices.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
