//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Stories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Stories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Pages.Stories", typeof(Stories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50th Anniversary.
        /// </summary>
        public static string AnnVid1 {
            get {
                return ResourceManager.GetString("AnnVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65th Anniversary.
        /// </summary>
        public static string AnnVid2 {
            get {
                return ResourceManager.GetString("AnnVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversaries.
        /// </summary>
        public static string CatAnniversary {
            get {
                return ResourceManager.GetString("CatAnniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children&apos;s.
        /// </summary>
        public static string CatChildren {
            get {
                return ResourceManager.GetString("CatChildren", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year.
        /// </summary>
        public static string CatNewYear {
            get {
                return ResourceManager.GetString("CatNewYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Projects.
        /// </summary>
        public static string CatOther {
            get {
                return ResourceManager.GetString("CatOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantic.
        /// </summary>
        public static string CatRomantic {
            get {
                return ResourceManager.GetString("CatRomantic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wedding.
        /// </summary>
        public static string CatWedding {
            get {
                return ResourceManager.GetString("CatWedding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal World.
        /// </summary>
        public static string ChildrenVid1 {
            get {
                return ResourceManager.GetString("ChildrenVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Journey.
        /// </summary>
        public static string ChildrenVid2 {
            get {
                return ResourceManager.GetString("ChildrenVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magic Christmas Tale.
        /// </summary>
        public static string NyVid1 {
            get {
                return ResourceManager.GetString("NyVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate New Year Celebration.
        /// </summary>
        public static string NyVid2 {
            get {
                return ResourceManager.GetString("NyVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year Midnight Countdown.
        /// </summary>
        public static string NyVid3 {
            get {
                return ResourceManager.GetString("NyVid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year Carnival.
        /// </summary>
        public static string NyVid4 {
            get {
                return ResourceManager.GetString("NyVid4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Year - Time of Magic.
        /// </summary>
        public static string NyVid5 {
            get {
                return ResourceManager.GetString("NyVid5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder&apos;s Day.
        /// </summary>
        public static string OthVid1 {
            get {
                return ResourceManager.GetString("OthVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maternity hospital.
        /// </summary>
        public static string OthVid2 {
            get {
                return ResourceManager.GetString("OthVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Facade Laser Mapping.
        /// </summary>
        public static string OthVid3 {
            get {
                return ResourceManager.GetString("OthVid3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love Confession.
        /// </summary>
        public static string RomVid1 {
            get {
                return ResourceManager.GetString("RomVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marriage Proposal.
        /// </summary>
        public static string RomVid2 {
            get {
                return ResourceManager.GetString("RomVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Laser Shows.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One in a Million.
        /// </summary>
        public static string WedVid1 {
            get {
                return ResourceManager.GetString("WedVid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together and Forever.
        /// </summary>
        public static string WedVid2 {
            get {
                return ResourceManager.GetString("WedVid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Can&apos;t Escape Fate.
        /// </summary>
        public static string WedVid3 {
            get {
                return ResourceManager.GetString("WedVid3", resourceCulture);
            }
        }
    }
}
