//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserShowSite.Resources.Pages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkSteps {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkSteps() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserShowSite.Resources.Pages.WorkSteps", typeof(WorkSteps).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate price.
        /// </summary>
        public static string CtaCalculator {
            get {
                return ResourceManager.GetString("CtaCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a request.
        /// </summary>
        public static string CtaRequest {
            get {
                return ResourceManager.GetString("CtaRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a request or calculate an approximate price. We will contact you and suggest the best laser show format..
        /// </summary>
        public static string CtaText {
            get {
                return ResourceManager.GetString("CtaText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to discuss your event?.
        /// </summary>
        public static string CtaTitle {
            get {
                return ResourceManager.GetString("CtaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clear step-by-step process from your request to a bright laser show at your event..
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event date and approximate time.
        /// </summary>
        public static string NeedItem1 {
            get {
                return ResourceManager.GetString("NeedItem1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City and venue.
        /// </summary>
        public static string NeedItem2 {
            get {
                return ResourceManager.GetString("NeedItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event format and approximate number of guests.
        /// </summary>
        public static string NeedItem3 {
            get {
                return ResourceManager.GetString("NeedItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor or outdoor location, screen, facade or projection surface.
        /// </summary>
        public static string NeedItem4 {
            get {
                return ResourceManager.GetString("NeedItem4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired duration, music and personal elements.
        /// </summary>
        public static string NeedItem5 {
            get {
                return ResourceManager.GetString("NeedItem5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is useful to prepare.
        /// </summary>
        public static string NeedTitle {
            get {
                return ResourceManager.GetString("NeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How We Work.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event date is booked after the details are approved and an advance payment is made. The remaining amount is usually paid on the event day. Exact payment terms are agreed individually and can be fixed in the agreement..
        /// </summary>
        public static string PaymentText {
            get {
                return ResourceManager.GetString("PaymentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement and payment.
        /// </summary>
        public static string PaymentTitle {
            get {
                return ResourceManager.GetString("PaymentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You leave a request on the website, contact us in a messenger or call us. We receive the basic information about your event..
        /// </summary>
        public static string Step1Text {
            get {
                return ResourceManager.GetString("Step1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Step1Title {
            get {
                return ResourceManager.GetString("Step1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We clarify the date, venue, event format, number of guests, indoor or outdoor conditions and your main wishes..
        /// </summary>
        public static string Step2Text {
            get {
                return ResourceManager.GetString("Step2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details discussion.
        /// </summary>
        public static string Step2Title {
            get {
                return ResourceManager.GetString("Step2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Together we choose the best format: animation show, beam show, combined show, ready-made story or custom scenario..
        /// </summary>
        public static string Step3Text {
            get {
                return ResourceManager.GetString("Step3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show format selection.
        /// </summary>
        public static string Step3Title {
            get {
                return ResourceManager.GetString("Step3Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We agree on the video story, music, names, date, logo, congratulation text and other personal elements..
        /// </summary>
        public static string Step4Text {
            get {
                return ResourceManager.GetString("Step4Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Story and music.
        /// </summary>
        public static string Step4Title {
            get {
                return ResourceManager.GetString("Step4Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We calculate the final cost based on the show type, duration, complexity, location and additional equipment if needed..
        /// </summary>
        public static string Step5Text {
            get {
                return ResourceManager.GetString("Step5Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price calculation.
        /// </summary>
        public static string Step5Title {
            get {
                return ResourceManager.GetString("Step5Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After all details are approved, we sign an agreement, fix the event date and receive an advance payment..
        /// </summary>
        public static string Step6Text {
            get {
                return ResourceManager.GetString("Step6Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement and advance payment.
        /// </summary>
        public static string Step6Title {
            get {
                return ResourceManager.GetString("Step6Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our team prepares graphics, adapts the selected story, adds personal elements and checks the technical part..
        /// </summary>
        public static string Step7Text {
            get {
                return ResourceManager.GetString("Step7Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preparation.
        /// </summary>
        public static string Step7Title {
            get {
                return ResourceManager.GetString("Step7Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the event day we arrive in advance, install the equipment, check the projection and prepare everything for the show..
        /// </summary>
        public static string Step8Text {
            get {
                return ResourceManager.GetString("Step8Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup at the venue.
        /// </summary>
        public static string Step8Title {
            get {
                return ResourceManager.GetString("Step8Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We run the laser show at the agreed time. The remaining payment is made on the event day unless otherwise agreed..
        /// </summary>
        public static string Step9Text {
            get {
                return ResourceManager.GetString("Step9Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show and final payment.
        /// </summary>
        public static string Step9Title {
            get {
                return ResourceManager.GetString("Step9Title", resourceCulture);
            }
        }
    }
}
